### ISSUE TITLE
Some keys appear to not register as key presses?

### ISSUE THREAD

**Issue by machooth** [supermarsx/magickeyboard#1]
Hello,

As I was trying to remap some of the keys via Microsoft PowerToys, I realized that some of the keys do not register when pressed individually. In particular all the F# keys (they only do when pressed with the fn key) and the fn key itself. Is there a way to "unlock" those that I cannot find?

Thank you

**Comment by supermarsx** [comment]
Hi, i saw this a couple of day ago and then forgot to answer. 

I tried to do what you're trying to but never found viable options, it's a real bummer. There may be a way maybe through the driver somehow but i'm not well versed in that, that would most probably involve reverse engineering, ida, recompiling, hack here and there, etc etc. 

Sorry, i'm unable to help with this specific thing you're asking.
